base:
  name: Insomnia Prediction
  random_seed: 42
  test_size : 0.2

data_source:
  local_data_source:
    raw_data: data/sleep_and_health_raw_data.csv
    pre_processed_data: data/preprocessed_data.csv
    data_sample: 500

metrics_path: 
  roc_auc : ROC_Curves.png
  confusion_mat : confusion_matrix.png


ml_flow_config:
  remote_server_uri: http://localhost:5000

  experiment_name: ML Experiment 
  run_name: ML Run 

  registered_model_name: insomnia_classifi_model.pkl

  production_model_path: predictionService/production_model.pkl

